export const jatincardatabase = {
  EngineTransmission: {
    Engine: ["796 cc"],
    EngineType: ["F8D"],
    FuelType: ["Petrol"],
    MaxPower: ["47 bhp @ 6000 rpm"],
    MaxTorque: ["69 Nm @ 3500 rpm"],
    Mileage: ["22.05 kmpl"],
    Drivetrain: ["FWD"],
    Transmission: ["Manual - 5 Gears"],
    EmissionStandard: ["BS 6"],
  },
  DimensionWeight: {
    Length: ["3445 mm"],
    Width: ["1515 mm"],
    Height: ["1475 mm"],
    Wheelbase: ["2360 mm"],
    GroundClearance: ["160 mm"],
  },
  SuspensionBrakeSteering: {
    FrontSuspension: ["Mac Pherson Strut"],
    RearSuspension: ["3-Link Rigid Axle Suspension"],
    FrontBrake: ["Disc"],
    RearBrake: ["Drum"],
    MinimumTurningRadius: ["4.6 metres"],
    SteeringType: ["Power assisted (Electric)"],
    Wheels: ["Steel Rims"],
    SpareWheel: ["Steel"],
    TyreSize: ["145 / 80 R12"],
  },
  Safety: {
    NCAPRating: ["Not Tested"],
    Airbags: ["2 Airbags (Driver, Passenger)"],
    MiddleRearSeatbelt: ["No"],
    MiddleRearHeadrest: ["No"],
    TyrePressureMoni: ["No"],
    ChildSeatAnchor: ["No"],
    SeatBeltWarning: ["Yes"],
  },
  BreakindAndTraction: {
    AntiLockBreaking: ["Yes"],
    ElectricBrakeDistri: ["Yes"],
    BrakeAssist: ["Yes"],
    ElectricStabilityProgram: ["No"],
    HillHoldControl: ["No"],
    TractionControlSys: ["No"],
    HillDescentControl: ["No"],
  },
  LocksAndSecurity: {
    EngineImmobilizer: ["Yes"],
    CentralLocking: ["Remote"],
    SpeedSensingDoorLock: ["No"],
    ChildSafetyLock: ["Yes"],
  },
  ConfortAndCOnvenience: {
    AirConditioner: ["Yes (Manual)"],
    FrontAC: ["Single Zone, Common Fan Speed Control"],
    RearAC: ["No"],
    Heater: ["Yes"],
    VanityMirror: ["No"],
    CabinBootAccess: ["Yes"],
    AntiGlareMirrors: ["No"],
    ParkingAssist: ["No"],
    ParkingSensors: ["Rear"],
    CruiseCOntrol: ["No"],
    HeadLightIgnitionONReminder: ["Yes"],
    KeylessStartStopButton: ["No"],
    SteeringAdjustment: ["No"],
    twelveVPowerOutlets: ["Yes"],
  },
  SeatsAndUpholstery: {
    DriverSeatAdjustment: [
      "4 way manually adjustable (seat forward / back, backrest tilt forward / back)",
    ],
    FrontPassengerSeatAdjustment: [
      "4 way manually adjustable (seat forward / back, backrest tilt forward / back)",
    ],
    RearRowSeatAdjustment: ["No"],
    SeatUpholstery: ["Vinyl + Fabric"],
    LeatherWrappedSteeringwheel: ["No"],
    LeatherWrappedGearKnob: ["No"],
    DriverArmrest: ["No"],
    RearPassengerSeatsType: ["Bench"],
    VentilatedSeats: ["No"],
    InteriorColors: ["Black and Beige"],
    RearArmrest: ["No"],
    FoldingRearSeat: ["Full"],
    SplitRearSeat: ["No"],
    FrontSeatbackPockets: ["Yes"],
    HeadRest: ["Front and Rear"],
  },
  Storage: {
    CupHolders: ["Front and Rear"],
    DriverArmrestStorage: ["No"],
    CooledGloveBox: ["No"],
    SunglassHOlder: ["No"],
  },
  DoorsWindowsMirrorsWipers: {
    PowerWindows: ["Front Only"],
    OneTouchDown: ["No"],
    OneTouchUp: ["No"],
    AdjustableORVM: ["Internally Adjustable"],
    TurnIndicatorsonORVM: ["No"],
    RearDefogger: ["No"],
    RearWiper: ["No"],
    ExteriorDoorHandles: ["Body Coloured"],
    RainSensingWipers: ["No"],
    InteriorDoorHandles: ["Silver"],
    DoorPockets: ["Front"],
    SideWindowBlinds: ["No"],
    BootLidOpener: ["Internal with Remote"],
    OutsideRearViewMirrors: ["Body Coloured"],
  },
  Exterior: {
    Sunroof: ["No"],
    RoofMountedAntenna: ["Yes"],
    BodyColorBumpers: ["Yes"],
    BodyKit: ["No"],
    RubStrips: ["Black"],
  },
  Lighting: {
    DaytimeRunningLights: ["No"],
    AmbientInteriorLighting: ["No"],
    PuddleLamps: ["No"],
    FogLights: ["Yes"],
    HeadLights: ["Halogen"],
    AutomaticHeadLamps: ["No"],
    FollowmeHomeLamps: ["No"],
    TailLight: ["Halogen"],
    CabinLamps: ["Front"],
    HeadLightHeightAdjuster: ["Yes"],
    GloveBoxLamp: ["No"],
    LightsonVanityMirrors: ["No"],
    RearReadingLamps: ["No"],
    COrneringHeadLights: ["No"],
  },
  Instrumentation: {
    InstrumentCluster: ["Analogue and Digital"],
    TripMeter: ["Electronic 2 trips"],
    AverageFuelConsumption: ["Yes"],
    AverageSpeed: ["No"],
    DistanceToEmpty: ["Yes"],
    Clock: ["Digital"],
    LowFuelLevelWarning: ["Yes"],
    DoorAjarWarning: ["No"],
    AdjustableClusterBrightness: ["No"],
    GearIndicator: ["No"],
    ShiftIndicator: ["No"],
    TachoMeter: ["No"],
    InstantaneousConsumption: ["No"],
  },
  EntertainmentInfoandCommunication: {
    WirelessCharger: ["No"],
    SmartConnectivity: ["Android Auto (Yes), Apple Car Play (Yes)"],
    HeadUnitSize: ["-"],
    IntegratedMusicSystem: ["Yes"],
    Display: ["TouchScreen"],
    GPSNavigationSystem: ["Yes"],
    Speakers: ["2"],
    USBCampatibility: ["Yes"],
    AUXCompatibility: ["Yes"],
    BluetoothCompatibility: ["Yes"],
    SteeringMountedControls: ["No"],
    VoiceCommand: ["No"],
    CDPlayer: ["No"],
  },
  ManufacturerWarranty: {
    WarrantyYears: ["2"],
    WarrantyKilometers: ["40000"],
    ExtendedWarranty: ["-"],
  },
};
