import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import "react-multi-carousel/lib/styles.css";
import styles from "../styles/Home.module.css";
import PopularCarsFrontPage from "../Components/FrontPage/popularcarsfrontpage";
import SimilarCarss from "../Components/SpecificCar/SimilarCars";
import PopularAlternativeCarComparision from "../Components/FrontPage/popularAlternativeCarComparision";
import Nav from "../Components/head";
import SearchBar from "../Components/FrontPage/SearchBar";
import BookData from "../Data.json";
import SearchBar1 from "../Components/FrontPage/SearchBar1";
import { TSpresso } from "../CarPicsUrl/Thumbnails";

export default function Home() {
  const CompanyName = "MarutiSuzuki";
  const CarPrice = "₹ 3.77 Lakh";

  const CarName = "Maruti S-Presso";
  const OnlyName = "S-Presso";
  const PopularCars = {
    car1: [
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/32958/tata-harrier-right-front-three-quarter58.jpeg?q=85",
      "Harrier",
      "₹ 14.30 Lakh Onwards",
    ],
    car2: [
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/52565/hector-exterior-right-front-three-quarter-3.jpeg?q=85",
      "Hector",
      "₹ 13.18 Lakh onwards0",
    ],
    car3: [
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Creta/6775/1584360708758/front-left-side-47.jpg?tr=w-456",
      "Creta",
      "Rs.10.16 Lakh onwards",
    ],
    car4: [
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Creta/6775/1584360708758/front-left-side-47.jpg?tr=w-456",
      "Creta",
      "Rs.10.16 Lakh onwards",
    ],
    car5: [
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Creta/6775/1584360708758/front-left-side-47.jpg?tr=w-456",
      "Creta",
      "Rs.10.16 Lakh onwards",
    ],
    car6: [
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Creta/6775/1584360708758/front-left-side-47.jpg?tr=w-456",
      "Creta",
      "Rs.10.16 Lakh onwards",
    ],
    car: [
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Creta/6775/1584360708758/front-left-side-47.jpg?tr=w-456",
      "Creta",
      "Rs.10.16 Lakh onwards",
    ],
  };
  return (
    <div>
      <Nav />
      <div className="relative   overflow-hidden">
        <SearchBar1 />

        {/* <SearchBar placeholder="Enter a Book Name..." data={BookData} /> */}
        <img
          src="https://c.wallhere.com/photos/84/6f/ultra_wide_car-24084.png!d"
          alt="Avatar"
          className="object-cover w-full h-full filter blur-sm"
        />
        {/* <b className="absolute text-red-600 font-bold">SSSSSSSSSSSSSSS</b> */}
        {/* <div className="absolute  w-full py-2.5 bottom-0 inset-x-0 bg-blue-400 text-white text-xs text-center">
          this is a text
        </div> */}
      </div>

      <div className="mx-56 xl:mx-40 md:mx-24 sm:mx-4">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Head>
          <title>
            {CompanyName} | {OnlyName}
          </title>
          <meta name="description" content={CarName} />
          <link
            rel="canonical"
            href={`https://jatincarappclient.vercel.app/marutisuzuki/s-presso`}
          />
          <meta property="og:title" content={`${CompanyName}| ${OnlyName}`} />
          <meta property="og:description" content={CarPrice} />
          <meta property="og:type" content="webiste" />
          <meta
            property="og:url"
            content={`https://jatincarappclient.vercel.app/marutisuzuki/s-presso`}
          />
          <meta property="og:site_name" content={`${CompanyName}`} />

          <meta property="og:image" content={TSpresso} />
          <meta property="og:image:secure_url" content={TSpresso} />
          <meta property="og:image:type" content="image/jpg" />
          <meta property="fb:app_id" content={`32423423`} />
        </Head> */}

        <div className="z-10">
          <div>
            <div className="font-bold text-3xl text-center mb-4">
              {" "}
              All Brands{" "}
            </div>
            <div className="grid grid-cols-5 md:grid-cols-4 sm:grid-cols-3 gap-4">
              <Link href="/marutisuzuki">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/maruti.jpg"
                    alt="img"
                  />
                  <div className="text-center">Maruti</div>
                </div>
              </Link>
              <Link href="/hyundai">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/hyundai.jpg"
                    alt="img"
                  />
                  <div className="text-center">Hyundai</div>
                </div>
              </Link>
              <Link href="/honda">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/honda.jpg"
                    alt="img"
                  />
                  <div className="text-center">Honda</div>
                </div>
              </Link>
              <Link href="/tata">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/tata.jpg"
                    alt="img"
                  />
                  <div className="text-center">Tata</div>
                </div>
              </Link>
              <Link href="/mahindra">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/mahindra.jpg"
                    alt="img"
                  />
                  <div className="text-center">Mahindra</div>
                </div>
              </Link>

              <Link href="/renault">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/renault.jpg"
                    alt="img"
                  />
                  <div className="text-center">Renault</div>
                </div>
              </Link>

              <Link href="/ford">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/ford.jpg"
                    alt="img"
                  />
                  <div className="text-center">Ford</div>
                </div>
              </Link>
              <Link href="/nissan">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/nissan.jpg"
                    alt="img"
                  />
                  <div className="text-center">Nissan</div>
                </div>
              </Link>
              <Link href="/datsun">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/datsun.jpg"
                    alt="img"
                  />
                  <div className="text-center">Datsun</div>
                </div>
              </Link>
              <Link href="/toyota">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/toyota.jpg"
                    alt="img"
                  />
                  <div className="text-center">Toyota</div>
                </div>
              </Link>
              <Link href="/mg">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/mg.jpg"
                    alt="img"
                  />
                  <div className="text-center">MG</div>
                </div>
              </Link>
              <Link href="/kia">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/kia.jpg"
                    alt="img"
                  />
                  <div className="text-center">Kia</div>
                </div>
              </Link>
              <Link href="/volkswagen">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/volkswagen.jpg"
                    alt="img"
                  />
                  <div className="text-center">Volkswagen</div>
                </div>
              </Link>
              <Link href="/skoda">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/skoda.jpg"
                    alt="img"
                  />
                  <div className="text-center">Skoda</div>
                </div>
              </Link>
              {/* <Link href="/jeep">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/jeep.jpg"
                    alt="img"
                  />
                  <div className="text-center">Jeep</div>
                </div>
              </Link>
              <Link href="/isuzu">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/isuzu.jpg"
                    alt="img"
                  />
                  <div className="text-center">ISuzu</div>
                </div>
              </Link>
              <Link href="/audi">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/audi.jpg"
                    alt="img"
                  />
                  <div className="text-center">Audi</div>
                </div>
              </Link>
              <Link href="/mercedes">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/mercedes-benz.jpg"
                    alt="img"
                  />
                  <div className="text-center">Mercedes-Benz</div>
                </div>
              </Link>
              <Link href="/bmw">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://stimg.cardekho.com/pwa/img/brandLogo_168x84/bmw.jpg"
                    alt="img"
                  />
                  <div className="text-center">BMW</div>
                </div>
              </Link>
              <Link href="/tvs">
                <div className="flex flex-col border-2 shadow-md hover:shadow-2xl">
                  <img
                    className="mt-4"
                    src="https://bd.gaadicdn.com/pwa/img/brandLogo_168x84/tvs.png"
                    alt="img"
                  />
                  <div className="text-center">TVS</div>
                </div>
              </Link> */}
            </div>
            <div>
              <div className="font-bold text-3xl text-center mb-4 mt-6">
                Popular Cars
              </div>
            </div>
          </div>
        </div>
      </div>
      <PopularCarsFrontPage PopularCars={PopularCars} />
      <div className="font-bold text-3xl text-center mb-4 mt-6">
        Popular Compare Cars
      </div>
      <PopularAlternativeCarComparision />
    </div>
  );
}
